# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
virtualenv:
  system_site_packages: false

python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install -U pip tox-travis coverage
script:
  - tox
cache:
  pip: true
  directories:
    - $HOME/miniconda
