channels:
  - defaults
  - conda-forge

dependencies:
  - pip
  - ipython
  - nbsphinx
  - numpydoc
  - sphinx>=2.0
  - h5py
  - python==3.9
  - pip:
    - numpy
    - scipy
    - read_acq
    - cached_property
    - bidict
    - pyyaml
    - rich
    - attrs
    - toml
    - dill
