name: Deploy
on:
  push:
    tags-ignore:
      - 'v*'

jobs:
  bump-version:
    name: SemVer Bump
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
      new_tag: ${{ steps.bump.outputs.new_tag }}
      previous_tag: ${{ steps.bump.outputs.previous_tag }}
      prevoius_version: ${{ steps.bump.outputs.previous_version }}
      release_type: ${{ steps.bump.outputs.release_type }}
      changelog: ${{ steps.bump.outputs.changelog }}

    steps:
      - uses: actions/checkout@v1
        # Ensure full history is gotten.
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Get New Version
        id: bump
        uses: mathieudutour/github-tag-action@v5.5
        with:
          default_bump: false

  test-deploy:
    name: Test Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # https://github.com/ansible/pylibssh/blob/1e7b17f/.github/workflows/build-test-n-publish.yml#L146-L151
      - name: Get history and tags for SCM versioning to work
        run: |
          git fetch --prune --unshallow
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git describe --tags
          git describe --tags $(git rev-list --tags --max-count=1)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install build
        run: |
          python -m pip install build
          python -m pip install setuptools_scm
          python setup.py --version
      - name: Create setuptools_scm env variable
        if: github.ref != 'refs/heads/master'
        shell: bash
        run: |
          wget https://gist.github.com/plaplant/0902f09e59166bac742bbd554f3cd2f9/raw/make_dev_version.sh -O ../make_dev_version.sh
          version=$(bash ../make_dev_version.sh)
          echo "SETUPTOOLS_SCM_PRETEND_VERSION=$version" >> $GITHUB_ENV
      - name: Build a binary wheel and a source tarball
        run: python -m build
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: bump-version
    steps:
      - uses: actions/checkout@master
      # https://github.com/ansible/pylibssh/blob/1e7b17f/.github/workflows/build-test-n-publish.yml#L146-L151
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install build
        run: |
          python -m pip install build
          python -m pip install setuptools_scm
          python setup.py --version
      - name: Create setuptools_scm env variable (dev)
        shell: bash
        run: |
          version={{ needs.bump-version.outputs.new_version}}
          echo "SETUPTOOLS_SCM_PRETEND_VERSION=$version" >> $GITHUB_ENV
      - name: Build a binary wheel and a source tarball
        run: python -m build
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
